"""initial_schema

Revision ID: 99f0cbcde06b
Revises: 
Create Date: 2024-11-05 14:19:02.993340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99f0cbcde06b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('core_values', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('work_culture', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('top_six', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('preference_rankings', sa.JSON(), nullable=True),
    sa.Column('additional_interests', sa.Text(), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('career_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('career_title', sa.String(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_profiles.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_profiles.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('postings_old')
    op.alter_column('postings', 'max_salary',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('postings', 'med_salary',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('postings', 'min_salary',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('postings', 'structured_description',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('postings', 'structured_description',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('postings', 'min_salary',
               existing_type=sa.Float(precision=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('postings', 'med_salary',
               existing_type=sa.Float(precision=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('postings', 'max_salary',
               existing_type=sa.Float(precision=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.create_table('postings_old',
    sa.Column('job_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pay_period', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('views', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('med_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('min_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('formatted_work_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('applies', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('remote_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('job_posting_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('application_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('application_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('formatted_experience_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('skills_desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('posting_domain', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sponsored', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('work_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('compensation_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('normalized_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('fips', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('processed_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_skills_desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extracted_skills', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), autoincrement=False, nullable=True),
    sa.Column('job_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('processed_min_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('processed_med_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('processed_max_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('processed_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('processed_work_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('original_listed_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('expiry', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('closed_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('listed_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('job_id', name='postings_pkey')
    )
    op.drop_table('chat_histories')
    op.drop_table('career_recommendations')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
